# Generated by Django 3.1.14 on 2022-02-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_servise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servise',
            new_name='Service',
        ),
    ]
