# Generated by Django 3.1.14 on 2022-02-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220203_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
                ('text', models.CharField(max_length=123)),
                ('text1', models.CharField(max_length=123)),
                ('text2', models.CharField(max_length=123)),
                ('text3', models.CharField(max_length=123)),
                ('text4', models.CharField(max_length=123)),
                ('rasm', models.ImageField(upload_to='Service/')),
            ],
        ),
    ]
