# Generated by Django 3.1.14 on 2022-02-04 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_service2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service2',
            name='text4',
        ),
    ]
