# Generated by Django 3.1.14 on 2022-02-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_service2_text4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servise3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='Servise3/')),
                ('title', models.CharField(max_length=1223)),
                ('text', models.CharField(max_length=1232)),
                ('text2', models.CharField(max_length=1232)),
            ],
        ),
    ]
