# Generated by Django 3.1.14 on 2022-02-04 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_servise3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servise3',
            new_name='Service3',
        ),
    ]
