# Generated by Django 3.1.14 on 2022-02-04 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_features1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Features1',
        ),
    ]
