# Generated by Django 3.1.14 on 2022-02-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_features1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1234)),
                ('rasm', models.ImageField(upload_to='Features1/')),
                ('titles', models.CharField(max_length=123)),
                ('text', models.CharField(max_length=123)),
                ('title1', models.CharField(max_length=1234)),
                ('rasm1', models.ImageField(upload_to='Features1/')),
                ('title1s', models.CharField(max_length=123)),
                ('text1', models.CharField(max_length=123)),
                ('title2', models.CharField(max_length=1234)),
                ('rasm2', models.ImageField(upload_to='Features1/')),
                ('title2s', models.CharField(max_length=123)),
                ('text2', models.CharField(max_length=123)),
            ],
        ),
    ]
