# Generated by Django 3.1.14 on 2022-02-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_features1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narxlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=121)),
                ('text', models.CharField(max_length=1234)),
            ],
        ),
    ]
