# Generated by Django 3.1.14 on 2022-02-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_narxlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narxlar2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
                ('rasm', models.ImageField(upload_to='Narxlar2/')),
                ('text', models.TextField()),
                ('title1', models.CharField(max_length=123)),
                ('rasm1', models.ImageField(upload_to='Narxlar2/')),
                ('text1', models.TextField()),
                ('title2', models.CharField(max_length=123)),
                ('rasm2', models.ImageField(upload_to='Narxlar2/')),
                ('text2', models.TextField()),
            ],
        ),
    ]
