# Generated by Django 3.1.14 on 2022-02-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_narxlar3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narxrasm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='Narxlar3/')),
            ],
        ),
        migrations.RemoveField(
            model_name='narxlar3',
            name='rasm',
        ),
    ]
