# Generated by Django 3.1.14 on 2022-02-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20220206_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narxlar33',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
                ('rasm1', models.ImageField(upload_to='Narxlar4/')),
                ('rasm2', models.ImageField(upload_to='Narxlar4/')),
                ('rasm3', models.ImageField(upload_to='Narxlar4/')),
                ('rasm4', models.ImageField(upload_to='Narxlar4/')),
                ('rasm5', models.ImageField(upload_to='Narxlar4/')),
                ('rasm6', models.ImageField(upload_to='Narxlar4/')),
                ('rasm7', models.ImageField(upload_to='Narxlar4/')),
                ('rasm8', models.ImageField(upload_to='Narxlar4/')),
            ],
        ),
        migrations.DeleteModel(
            name='Narxlar3',
        ),
        migrations.DeleteModel(
            name='Narxrasm',
        ),
    ]
