# Generated by Django 3.1.14 on 2022-02-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='YoutubeVideo')),
                ('video', models.CharField(max_length=234)),
            ],
        ),
        migrations.DeleteModel(
            name='YouTube',
        ),
    ]
